version: '3.8'

services:
  # 1. API
  api:
    build: ./sentinel-api           # Busca el Dockerfile en esa carpeta
    container_name: sentinel-api-v3
    ports:
      - "8000:8000"                 # Exponemos el puerto para que los Agentes puedan mandar datos
    env_file:
      - ./sentinel-api/.env
    environment:
      - PYTHONUNBUFFERED=1        # Inyecta la llave secreta de forma segura
    depends_on:
      - db                          # Evita que arranque hasta que la base de datos esté lista

  # 2. Base de datos Cassandra DB
  db:
    image: cassandra:latest         # Descarga la imagen oficial de Cassandra
    container_name: sentinel-cassandra
    ports:
      - "9042:9042"                 # El puerto estándar donde Cassandra escucha peticiones
    environment:
      - CASSANDRA_CLUSTER_NAME=SentinelCluster
      - CASSANDRA_MAX_HEAP_SIZE=512M
      - CASSANDRA_HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    volumes:
      - cassandra_data:/var/lib/cassandra  # Persistencia de datos
    # Límite de memoria para que no congele la computadora
volumes:
  cassandra_data: