services:
  # 1. API - Sentinel
  api:
    build: ./sentinel-api
    container_name: sentinel-api-v3
    ports:
      - "8000:8000"
    env_file:
      - ./sentinel-api/.env
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 256M